version: "3"

services:
  app:
    container_name: cliente-satisfacao
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /home/node/app
    command: npm run start:dev
    environment:
      DATABASE_DOCKER_HOST: mysql
      DATABASE_HOST: 0.0.0.0
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: '123'
      DATABASE_DATABASE: cliente_satisfeito
      DATABASE_TYPE: mysql
      DATABASE_LOG: 'true'
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'cliente_satisfeito'
      MYSQL_USER: 'kauan'
      MYSQL_PASSWORD: '123'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db_data:

networks:
  default:
    driver: bridge
